# Generated by Django 3.1.4 on 2020-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlideShow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
